### ISSUE TITLE
Caused by: javax.servlet.jsp.JspException: The tag mapping was not found!

### ISSUE THREAD

**Issue by ptahchiev** [reinra/dynaform#4]
Hi there,

I tried running `mvn jetty:run` and then open http://localhost:8080/dynaform and then select one of the XSDs, but I see an error page and this error is printed in the console:
````
Caused by: javax.servlet.jsp.JspException: The tag mapping was not found!.
	at org.araneaframework.jsp.tag.uilib.form.element.AutomaticTagFormElementTag.doStartTag(AutomaticTagFormElementTag.java:96)
	at org.araneaframework.jsp.tag.BaseTag.doStartTag(BaseTag.java:90)
	at org.apache.jsp.WEB_002dINF.jsp.form.standard_jsp._jspx_meth_ui_automaticFormElement_1(org.apache.jsp.WEB_002dINF.jsp.form.standard_jsp:380)
	at org.apache.jsp.WEB_002dINF.jsp.form.standard_jsp._jspx_meth_c_forEach_1(org.apache.jsp.WEB_002dINF.jsp.form.standard_jsp:320)
	at org.apache.jsp.WEB_002dINF.jsp.form.standard_jsp._jspx_meth_c_when_1(org.apache.jsp.WEB_002dINF.jsp.form.standard_jsp:283)
	at org.apache.jsp.WEB_002dINF.jsp.form.standard_jsp._jspx_meth_c_choose_0(org.apache.jsp.WEB_002dINF.jsp.form.standard_jsp:162)
	at org.apache.jsp.WEB_002dINF.jsp.form.standard_jsp._jspx_meth_ui_form_0(org.apache.jsp.WEB_002dINF.jsp.form.standard_jsp:132)
	at org.apache.jsp.WEB_002dINF.jsp.form.standard_jsp._jspx_meth_ui_widgetContext_0(org.apache.jsp.WEB_002dINF.jsp.form.standard_jsp:102)
	at org.apache.jsp.WEB_002dINF.jsp.form.standard_jsp._jspService(org.apache.jsp.WEB_002dINF.jsp.form.standard_jsp:76)
	... 303 more

````

**Comment by ptahchiev** [comment]
OK found it. I had to declare the jetty plugin like this:

````
            <plugin>
                <groupId>org.mortbay.jetty</groupId>
                <artifactId>maven-jetty-plugin</artifactId>
                <version>6.1.10</version>
                <dependencies>
                    <dependency>
                        <groupId>org.araneaframework</groupId>
                        <artifactId>aranea</artifactId>
                        <version>1.1.6</version>
                    </dependency>
                    <dependency>
                        <groupId>org.araneaframework</groupId>
                        <artifactId>aranea-examples-common</artifactId>
                        <version>1.1.6</version>
                    </dependency>
                </dependencies>
            </plugin>
````
